services:
  - type: web
    name: expressapi
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node hsrServer.js
    envVars:
      - key: NODE_VERSION
        value: 20.20.2
